### ISSUE TITLE
Slim incompatibility

### ISSUE THREAD

**Issue by joel** [scottvrosenthal/twitter-bootswatch-rails#36]
Hi I don't know if this error comes from slim or less but I tried with 2 fresh apps, one with haml and other with slim and still this error with slim.

ruby 2.2.1
rails 4.2.1

slim-rails', git: 'git@github.com:slim-template/slim-rails.git
revision: 7f2a0542f8dacb3fb661c08a004cefc83c4684a2

twitter-bootswatch-rails (3.3.2.0)
twitter-bootswatch-rails-fontawesome (4.3.0.0)
twitter-bootswatch-rails-helpers (3.3.2.0)
less-rails (2.6.0)

![capture d ecran 2015-04-16 19 29 16](https://cloud.githubusercontent.com/assets/5789/7187257/a4ef5b44-e46f-11e4-8294-198f7c75acec.png)

![capture d ecran 2015-04-16 19 29 43](https://cloud.githubusercontent.com/assets/5789/7187258/a4f0798e-e46f-11e4-9e65-9f1c38d7b5ee.png)

**Comment by marlonoso** [comment]
Install new version of less-rails

gem 'less-rails', '~> 2.7.0'
then run: bundle update less-rails

https://github.com/metaskills/less-rails/issues/100#issuecomment-93969641

**Comment by scottvrosenthal** [comment]
@joel did running `bundle update less-rails` resolve this for you?

**Comment by scottvrosenthal** [comment]
Resolved it for me locally so closing.
