### ISSUE TITLE
Need to add assets to config/initializers/assets.rb

### ISSUE THREAD

**Issue by GabrielLidenor** [scottvrosenthal/twitter-bootswatch-rails#37]
Right after running the commands: 

rails g bootswatch:install cyborg
rails g bootswatch:import cyborg
rails g bootswatch:layout cyborg

And then running the server, it shows theses errors: 
ActionView::Template::Error (Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( paper.css )` to `config/initializers/assets.rb` and restart your server):
     9:     / Le HTML5 shim, for IE6-8 support of HTML elements
    10:     /[if lt IE 9]
    11:       = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    12:     = stylesheet_link_tag "paper", :media => "all"
    13:     = yield(:page_stylesheet) if content_for?(:page_stylesheet)
    14: 
    15: 
  app/views/layouts/application.html.slim:12:in `_app_views_layouts_application_html_slim__1353161148096045749_70231942046980'

ActionView::Template::Error (Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( paper.js )` to `config/initializers/assets.rb` and restart your server):
    21:       | Javascripts
    22:       | \==================================================
    23:     /! Placed at the end of the document so the pages load faster
    24:     = javascript_include_tag "paper"
    25:     = yield(:page_javascript) if content_for?(:page_javascript)
  app/views/layouts/application.html.slim:24:in `_app_views_layouts_application_html_slim__3094833032574479388_70210147487240'

Then I needed to add the assets in the assets.rb

**Comment by scottvrosenthal** [comment]
@GabrielLidenor what version of rails are you trying this with?  Also, please pull down the demo via a git clone and if that doesn't run correctly for you it may be another issue.

**Comment by paingsoethaw** [comment]
I think that link would help you.

http://stackoverflow.com/questions/23673036/asset-filtered-out-and-will-not-be-served

**Comment by scottvrosenthal** [comment]
Closing this as this is just a configuration customization issue in your project:

https://github.com/scottvrosenthal/twitter-bootswatch-rails#adding-custom-assets-to-the-asset-pipeline-when-deploying
